name: Build & Test

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Setup Project
      run: make setup

    - name: Build
      run: make build

    - name: Test
      run: make test
